version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  executor_node_18:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/rollup-plugin-export-equals

commands:
  command_ci:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-rpexeq-{{ checksum "package-lock.json" }}
            - v1-deps-rpexeq-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-deps-rpexeq-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build

  command_save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/rollup-plugin-export-equals
          paths:
            - .

  command_restore_workspace:
    steps:
      - attach_workspace:
          at: ~/rollup-plugin-export-equals

  command_npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_ci:
    executor: executor_node_18
    steps:
      - command_ci
      - command_save_workspace

  job_upload_coverage:
    executor: executor_node_18
    steps:
      - command_restore_workspace
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    executor: executor_node_18
    steps:
      - command_restore_workspace
      - command_npm_publish

workflows:
  workflow_ci:
    jobs:
      - job_ci:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_ci
          filters:
            branches:
              only: /master/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_ci
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
