name: Create GitHub Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Build
        run: npm run build

      - name: Create Tarball
        run: npm pack

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: rollup-plugin-export-equals-*.tgz
          make_latest: true
